### ISSUE TITLE
Minor problem

### ISSUE THREAD

**Issue by EternalWind** [tristanguigue/dynamic-programing#1]
I think the 25th line in the topdown sample of counting paths should be `cache[x1, y1] = count` rather than `cache[x1, x2]` which makes little sense to me.

**Comment by tristanguigue** [comment]
That's right, there was a mistake, it's been fixed now: https://github.com/tristanguigue/dynamic-programing/commit/8d7d4542929da379e62edf20260155ce25313f5d
Thanks for pointing that out!
